# Generated by Django 6.0.4 on 2026-04-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_rename_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['title']},
        ),
    ]
