# Generated by Django 6.0.4 on 2026-04-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_workflow_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
